### ISSUE TITLE
My Units no longer have colour circles [Dev2]

### ISSUE THREAD

**Issue by connordeckers** [UTAS-HealthSciences/mylo-mate#131]
With the updated My Units widget in Dev2, the coloured circles are missing. Look into re-adding the colour indicators.

**Comment by connordeckers** [comment]
Instead of coloured circles, perhaps consider a coloured border? Less likely to throw off layout, and possibly more visible. 

Quick example:
```css
.d2l-image-tile-0 .d2l-image-tile-image-container.style-scope.d2l-image-tile {
    border: 3px solid #2ea02e; /* Green colour for active */
    border: 3px solid transparent; /* Transparent border for inactive|unset. Stops size popping. */
}
```
